### ISSUE TITLE
🐙 Prysm Documentation Community Feedback 🐙

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#137]
Yesterday, we ran a [survey](https://forms.gle/djKwoCCQH8XK673j7) specifically targeting the Prysm community and contributors to let us know how they feel about the project. We received some high quality submissions and had a section where users could tell us how they feel about the docs. Here are the paraphrased, actionable responses:

- [x] Instructions on how to run your own eth1 node and point prysm to it
- [ ] An explainer regarding how key management works: i.e. where are the keys stored, what format are they in. If I want to take out my withdrawal private key and put it in cold storage, how would I do that? _IDEA: perhaps we can have a dedicated sidebar section to validator accounts / keys with various pages?_
- [x] We need more clarity on hardware. Not just tech specs but form factor. Are server comps going to be best because they are built to run 24/7 or will a NUC have just as much uptime/longevity? Perhaps some best practices for operating and maintaining hardware while running nodes (How to transfer your validator(s) to a new SSD if you have a hardware issue or just need to upgrade for storage)
- [x] Info on how to do a voluntary exit
- [x] Grafana info is important, we need the links to be fixed

These items can be split into separate tracking issues if needed to resolve. cc: @har00ga

**Comment by har00ga** [comment]
Related: #23

**Comment by har00ga** [comment]
* We need more clarity on hardware.
* An explainer regarding how key management works
* The How Prysm Works section needs to be less high-level and more architectural, clear, and useful

All these topics definitely deserve their own tracker issues!
