### ISSUE TITLE
TRACKER ISSUE: Monthly documentation sweeps

### ISSUE THREAD

**Issue by har00ga** [prysmaticlabs/documentation#37]
Hi team,

This is a tracking issue to keep tabs of the compiled lists of necessary changes after each future monthly documentation sweep. If you're completely lost right now, reach out to Preston. :)

The idea is to take 15 mins to a half hour once a month to read the manual cover-to-cover as group and collab to figure out what needs changing/removing/adding and discuss recent repeat questions to add onto the FAQ or elaborate on. At the end of each month, I'll upload them into checklist form here to cover progress.

**DAY OF MONTH:** 3rd Tuesday
**TIME OF DAY:** 5 PM UTC

**DATE OF NEXT MEETING:** May 18 2020

**Comment by prestonvanloon** [comment]
Third Tuesday of every month, starting tomorrow. 5 PM UTC

**Comment by har00ga** [comment]
April meeting notes
- [ ] Find solution for page previews on Discord etc.
- [ ] Dependencies missing from script install pages
- [ ] -d flag added for detachable window
- [ ] Change beacon node sync note, may take +12 hours
- [ ] New page - 'Lifecycle of a Validator' - needs own issue 
- [ ] Port 13000 opened, script pages
- [ ] Ethdo page still present
- [ ] Grafitti flag
- [ ] 64 bit only on ARM

The rest are in existing issues or the hackMD pad

Thanks @prestonvanloon & @terencechain :slightly_smiling_face: :heart:

**Comment by rauljordan** [comment]
Another item is to add the troubleshooting pages (maybe our FAQ can be sufficient for this)

**Comment by har00ga** [comment]
Indeed, that's where I was intending on putting the FAQ stuff :slightly_smiling_face: Figured it could be broken up by OS, though can change it to a single doc if preferred!

**Comment by har00ga** [comment]
May meeting notes

- [ ] Broken image, architecture page
- [ ] Migrate all images locally
- [ ] Available parameters, feature flags change
- [ ] Discord links changeout
- [ ] Consolidate how prysm works section

Much lighter this round. Thanks everyone!

**Comment by rauljordan** [comment]
Stale issue, we should use a new tracking issue or smaller issues for these future items
